/**
 * Phonostack — Sound Design Recipe Presets
 *
 * 8 built-in starter recipes that encode professional
 * sound-design structures as reusable layer compositions.
 */

import type { SoundDesignRecipe } from "./recipe-schema";

export const BUILT_IN_RECIPES: SoundDesignRecipe[] = [
  // ── 1. Cinematic Impact ────────────────────────────────────
  {
    id: "recipe-builtin-cinematic-impact",
    name: "Cinematic Impact",
    slug: "cinematic-impact",
    description: "Multi-layered cinematic impact with sub weight, transient attack, body mass, reverb tail, and design sweetener. Professional trailer/film hit.",
    category: "cinematic",
    tags: ["impact", "hit", "trailer", "cinematic", "boom"],
    icon: "Zap",
    layers: [
      {
        role: "sub_layer",
        label: "Sub Impact",
        promptTemplate: "deep sub-bass impact boom, {material} collision, felt more than heard, 20-60Hz, no high frequencies",
        frequencyRole: "sub",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "body",
        label: "Impact Body",
        promptTemplate: "heavy {material} impact body, weighty low-mid thud, {intensity} force, close perspective",
        frequencyRole: "low_body",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "transient",
        label: "Attack Transient",
        promptTemplate: "sharp {material} transient crack, fast attack, percussive snap, very short",
        frequencyRole: "transient_click",
        duration: { min: 0.5, max: 1.5 },
        promptInfluence: 0.5,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "tail",
        label: "Reverb Tail",
        promptTemplate: "long reverberant decay, {material} impact tail, wide stereo, cathedral-like room reflection fading to silence",
        frequencyRole: "wide",
        duration: { min: 3, max: 8 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 3,
      },
      {
        role: "sweetener",
        label: "Design Sweetener",
        promptTemplate: "cinematic impact sweetener, bright sparkle detail, ear candy shimmer after hit, ethereal high-frequency accent",
        frequencyRole: "air",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: true,
        priority: 4,
      },
    ],
    variationAxes: [
      { name: "material", label: "Material", values: ["metal", "stone", "wood", "glass", "earth"], affectsLayers: [0, 1, 2, 3], promptModifier: "replace" },
      { name: "intensity", label: "Intensity", values: ["light", "medium", "heavy", "massive"], affectsLayers: [1], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no dialogue", "no tonal elements"],
    duration: { min: 2, max: 8, default: 4 },
    recommendedBatchCount: 8,
    exportNaming: { template: "{category}_Impact_{material}_{intensity}_v{version}", variables: ["category", "material", "intensity", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 2. Sci-Fi Door ─────────────────────────────────────────
  {
    id: "recipe-builtin-scifi-door",
    name: "Sci-Fi Door",
    slug: "sci-fi-door",
    description: "Futuristic door mechanism with servo motor, hydraulic release, metal panel slide, mechanical body, air suction tail, and optional UI beep.",
    category: "sci-fi",
    tags: ["door", "sci-fi", "mechanism", "futuristic", "hatch"],
    icon: "DoorOpen",
    layers: [
      {
        role: "mechanical",
        label: "Servo Motor",
        promptTemplate: "electric servo motor movement, {size} mechanism, whirring mechanical gear, futuristic, precise",
        frequencyRole: "upper_mid",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "body",
        label: "Hydraulic Release",
        promptTemplate: "hydraulic pressure release, {speed} pneumatic hiss, compressed air burst, industrial",
        frequencyRole: "mid_detail",
        duration: { min: 0.5, max: 2 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "movement",
        label: "Metal Panel Slide",
        promptTemplate: "heavy metal panel sliding on rails, {size} door, scraping friction, sci-fi spaceship interior",
        frequencyRole: "low_mid",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "sub_layer",
        label: "Mechanical Body",
        promptTemplate: "deep low-frequency mechanical rumble, {size} machinery vibration, felt not heard",
        frequencyRole: "low_body",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 3,
      },
      {
        role: "tail",
        label: "Air Suction Tail",
        promptTemplate: "subtle air suction seal, vacuum seal closing, gentle pressurization, {speed} decompression fade",
        frequencyRole: "high_texture",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 4,
      },
      {
        role: "sweetener",
        label: "UI Confirmation Beep",
        promptTemplate: "short electronic confirmation beep, clean digital tone, futuristic UI acknowledgment, subtle",
        frequencyRole: "upper_mid",
        duration: { min: 0.5, max: 1 },
        promptInfluence: 0.5,
        loop: false,
        optional: true,
        priority: 5,
      },
    ],
    variationAxes: [
      { name: "size", label: "Door Size", values: ["small", "medium", "large", "massive"], affectsLayers: [0, 2, 3], promptModifier: "replace" },
      { name: "speed", label: "Speed", values: ["slow", "normal", "fast"], affectsLayers: [1, 4], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no dialogue", "no organic sounds"],
    duration: { min: 1, max: 5, default: 3 },
    recommendedBatchCount: 6,
    exportNaming: { template: "SciFi_Door_{size}_{speed}_v{version}", variables: ["size", "speed", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 3. Wet Footstep ────────────────────────────────────────
  {
    id: "recipe-builtin-wet-footstep",
    name: "Wet Footstep",
    slug: "wet-footstep",
    description: "Detailed footstep with impact body, water splash layer, shoe material texture, and surface detail. Game/film-ready.",
    category: "foley",
    tags: ["footstep", "water", "wet", "foley", "walk"],
    icon: "Footprints",
    layers: [
      {
        role: "impact",
        label: "Step Impact",
        promptTemplate: "{weight} foot impact on {surface}, boot sole hitting ground, close perspective, {speed} pace",
        frequencyRole: "low_mid",
        duration: { min: 0.5, max: 1.5 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "texture",
        label: "Water Splash",
        promptTemplate: "small water splash, foot stepping into shallow puddle, {weight} water displacement, wet splatter",
        frequencyRole: "mid_detail",
        duration: { min: 0.5, max: 1 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "body",
        label: "Shoe Material",
        promptTemplate: "{surface} shoe material creak, leather/rubber flex on {speed} step, close microphone perspective",
        frequencyRole: "upper_mid",
        duration: { min: 0.3, max: 0.8 },
        promptInfluence: 0.3,
        loop: false,
        optional: true,
        priority: 2,
      },
      {
        role: "transient",
        label: "Surface Debris",
        promptTemplate: "tiny debris scatter from footstep, small rocks and grit displaced, {surface} ground particles",
        frequencyRole: "high_texture",
        duration: { min: 0.3, max: 0.6 },
        promptInfluence: 0.3,
        loop: false,
        optional: true,
        priority: 3,
      },
    ],
    variationAxes: [
      { name: "surface", label: "Surface", values: ["concrete", "wood", "metal", "gravel", "tile", "mud"], affectsLayers: [0, 2, 3], promptModifier: "replace" },
      { name: "speed", label: "Speed", values: ["slow walk", "normal walk", "fast walk", "run"], affectsLayers: [0, 2], promptModifier: "replace" },
      { name: "weight", label: "Weight", values: ["light", "medium", "heavy"], affectsLayers: [0, 1], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no dialogue", "no ambience"],
    duration: { min: 0.5, max: 2, default: 1 },
    recommendedBatchCount: 12,
    exportNaming: { template: "Footstep_Wet_{surface}_{speed}_{take}", variables: ["surface", "speed", "take"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 4. Creature Attack ─────────────────────────────────────
  {
    id: "recipe-builtin-creature-attack",
    name: "Creature Attack",
    slug: "creature-attack",
    description: "Multi-layer creature attack with vocalization, movement whoosh, physical impact, and organic texture.",
    category: "game",
    tags: ["creature", "attack", "monster", "game", "combat"],
    icon: "Bug",
    layers: [
      {
        role: "vocal_layer",
        label: "Vocal Growl/Roar",
        promptTemplate: "{creature_size} creature aggressive vocalization, growl transitioning to attack roar, {intensity} ferocity, organic",
        frequencyRole: "mid_detail",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "movement",
        label: "Attack Whoosh",
        promptTemplate: "fast attack whoosh, {creature_size} limb swing through air, aggressive movement, {intensity} velocity",
        frequencyRole: "upper_mid",
        duration: { min: 0.5, max: 1.5 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "impact",
        label: "Physical Impact",
        promptTemplate: "{intensity} physical impact, claw or bite hitting target, flesh and bone collision, close perspective",
        frequencyRole: "low_mid",
        duration: { min: 0.5, max: 1.5 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "organic",
        label: "Organic Texture",
        promptTemplate: "wet organic texture, {creature_size} creature skin and muscle movement, biological detail, slimy",
        frequencyRole: "high_texture",
        duration: { min: 0.5, max: 2 },
        promptInfluence: 0.3,
        loop: false,
        optional: true,
        priority: 3,
      },
    ],
    variationAxes: [
      { name: "creature_size", label: "Creature Size", values: ["small", "medium", "large", "massive"], affectsLayers: [0, 1, 3], promptModifier: "replace" },
      { name: "intensity", label: "Intensity", values: ["light", "medium", "heavy", "devastating"], affectsLayers: [0, 1, 2], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no human speech", "no mechanical sounds"],
    duration: { min: 1, max: 4, default: 2 },
    recommendedBatchCount: 8,
    exportNaming: { template: "Creature_Attack_{creature_size}_{intensity}_v{version}", variables: ["creature_size", "intensity", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 5. Horror Room Tone ────────────────────────────────────
  {
    id: "recipe-builtin-horror-room-tone",
    name: "Horror Room Tone",
    slug: "horror-room-tone",
    description: "Unsettling room tone with deep drone, high texture, random organic elements, and distant environmental detail.",
    category: "horror",
    tags: ["horror", "ambience", "room tone", "tension", "atmosphere"],
    icon: "Ghost",
    layers: [
      {
        role: "sub_layer",
        label: "Deep Drone",
        promptTemplate: "ominous deep drone, {darkness} tension, sub-frequency rumble, felt more than heard, oppressive, unsettling",
        frequencyRole: "sub",
        duration: { min: 8, max: 22 },
        promptInfluence: 0.3,
        loop: true,
        optional: false,
        priority: 0,
      },
      {
        role: "texture",
        label: "High Tension Texture",
        promptTemplate: "eerie high-frequency texture, thin metallic resonance, {darkness} dissonant shimmer, barely audible",
        frequencyRole: "high_texture",
        duration: { min: 8, max: 22 },
        promptInfluence: 0.3,
        loop: true,
        optional: false,
        priority: 1,
      },
      {
        role: "organic",
        label: "Random Organic Detail",
        promptTemplate: "subtle organic movement, {space_size} room, distant wet dripping, creaking wood or bone, sparse and unpredictable",
        frequencyRole: "mid_detail",
        duration: { min: 5, max: 15 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "space",
        label: "Distant Environmental",
        promptTemplate: "distant muffled environmental element, {space_size} space, wind through walls, faraway rumble, horror atmosphere",
        frequencyRole: "wide",
        duration: { min: 8, max: 22 },
        promptInfluence: 0.2,
        loop: true,
        optional: true,
        priority: 3,
      },
    ],
    variationAxes: [
      { name: "darkness", label: "Darkness Level", values: ["subtle unease", "moderate tension", "deep dread", "extreme terror"], affectsLayers: [0, 1], promptModifier: "replace" },
      { name: "space_size", label: "Space Size", values: ["cramped", "medium", "cavernous", "vast void"], affectsLayers: [2, 3], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no dialogue", "no jump scares", "no sudden loud sounds"],
    duration: { min: 8, max: 22, default: 15 },
    recommendedBatchCount: 4,
    exportNaming: { template: "Horror_RoomTone_{darkness}_{space_size}_v{version}", variables: ["darkness", "space_size", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 6. Premium UI Notification ─────────────────────────────
  {
    id: "recipe-builtin-ui-notification",
    name: "Premium UI Notification",
    slug: "premium-ui-notification",
    description: "Clean, premium notification sound with tonal body, transient click, and sparkle sweetener. App/game-ready.",
    category: "ui",
    tags: ["ui", "notification", "alert", "interface", "premium"],
    icon: "Bell",
    layers: [
      {
        role: "transient",
        label: "Transient Click",
        promptTemplate: "clean digital click, precise attack, {urgency} notification onset, no reverb, very short",
        frequencyRole: "transient_click",
        duration: { min: 0.1, max: 0.3 },
        promptInfluence: 0.5,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "body",
        label: "Tonal Body",
        promptTemplate: "pleasant {brand_tone} tonal chime, clean sine-like pitch, {urgency} notification, smooth and satisfying",
        frequencyRole: "mid_detail",
        duration: { min: 0.3, max: 1 },
        promptInfluence: 0.5,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "sweetener",
        label: "Sparkle Sweetener",
        promptTemplate: "delicate sparkle accent, airy high-frequency shimmer, {brand_tone} character, ethereal detail after notification",
        frequencyRole: "air",
        duration: { min: 0.3, max: 0.8 },
        promptInfluence: 0.3,
        loop: false,
        optional: true,
        priority: 2,
      },
    ],
    variationAxes: [
      { name: "urgency", label: "Urgency", values: ["gentle", "neutral", "important", "critical"], affectsLayers: [0, 1], promptModifier: "replace" },
      { name: "brand_tone", label: "Brand Tone", values: ["warm wooden", "bright crystalline", "soft organic", "modern synthetic", "minimal clean"], affectsLayers: [1, 2], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no reverb", "no noise", "no distortion"],
    duration: { min: 0.2, max: 1.5, default: 0.6 },
    recommendedBatchCount: 10,
    exportNaming: { template: "UI_Notification_{urgency}_{brand_tone}_v{version}", variables: ["urgency", "brand_tone", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 7. Magical Transition ──────────────────────────────────
  {
    id: "recipe-builtin-magical-transition",
    name: "Magical Transition",
    slug: "magical-transition",
    description: "Fantasy spell/portal transition with low whoosh, tonal shimmer, sparkle particles, and reverberant tail.",
    category: "fantasy",
    tags: ["magic", "spell", "portal", "transition", "fantasy", "whoosh"],
    icon: "Sparkles",
    layers: [
      {
        role: "body",
        label: "Low Whoosh",
        promptTemplate: "{element} magical whoosh, {power_level} energy surge, low-frequency sweep, smooth arc movement",
        frequencyRole: "low_body",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "texture",
        label: "Tonal Shimmer",
        promptTemplate: "ethereal tonal shimmer, {element} magical resonance, crystalline mid-frequency glow, {power_level} intensity",
        frequencyRole: "mid_detail",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "sweetener",
        label: "Sparkle Particles",
        promptTemplate: "magical sparkle particles, high-frequency fairy dust, {element} glitter cascade, delicate and airy",
        frequencyRole: "air",
        duration: { min: 1, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "tail",
        label: "Reverberant Tail",
        promptTemplate: "long magical reverb tail, {element} energy dissipating, wide stereo decay, otherworldly space",
        frequencyRole: "wide",
        duration: { min: 3, max: 8 },
        promptInfluence: 0.2,
        loop: false,
        optional: true,
        priority: 3,
      },
    ],
    variationAxes: [
      { name: "element", label: "Element", values: ["fire", "ice", "lightning", "nature", "arcane", "shadow", "light"], affectsLayers: [0, 1, 2, 3], promptModifier: "replace" },
      { name: "power_level", label: "Power Level", values: ["subtle", "moderate", "powerful", "epic"], affectsLayers: [0, 1], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no dialogue", "no realistic sounds"],
    duration: { min: 1, max: 6, default: 3 },
    recommendedBatchCount: 6,
    exportNaming: { template: "Magic_Transition_{element}_{power_level}_v{version}", variables: ["element", "power_level", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },

  // ── 8. Trailer Whoosh ──────────────────────────────────────
  {
    id: "recipe-builtin-trailer-whoosh",
    name: "Trailer Whoosh",
    slug: "trailer-whoosh",
    description: "Dramatic trailer whoosh/riser with sub rumble, mid swoosh, high air, and transient punctuation.",
    category: "trailer",
    tags: ["trailer", "whoosh", "riser", "transition", "swoosh"],
    icon: "Wind",
    layers: [
      {
        role: "sub_layer",
        label: "Sub Rumble",
        promptTemplate: "deep sub-frequency rumble, {weight} mass moving, building {speed} momentum, no high frequencies",
        frequencyRole: "sub",
        duration: { min: 1, max: 4 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 0,
      },
      {
        role: "movement",
        label: "Mid Swoosh",
        promptTemplate: "{speed} mid-frequency swoosh, {direction} movement arc, smooth trajectory, {weight} presence, cinematic",
        frequencyRole: "mid_detail",
        duration: { min: 0.5, max: 3 },
        promptInfluence: 0.4,
        loop: false,
        optional: false,
        priority: 1,
      },
      {
        role: "texture",
        label: "High Air",
        promptTemplate: "high-frequency air rush, {speed} wind texture, bright breathy detail, airy whoosh top end",
        frequencyRole: "air",
        duration: { min: 0.5, max: 3 },
        promptInfluence: 0.3,
        loop: false,
        optional: false,
        priority: 2,
      },
      {
        role: "transient",
        label: "Transient Punctuation",
        promptTemplate: "sharp transient punctuation at whoosh peak, {weight} snap, fast percussive accent, very short",
        frequencyRole: "transient_click",
        duration: { min: 0.2, max: 0.5 },
        promptInfluence: 0.5,
        loop: false,
        optional: true,
        priority: 3,
      },
    ],
    variationAxes: [
      { name: "speed", label: "Speed", values: ["slow", "medium", "fast", "hyper"], affectsLayers: [0, 1, 2], promptModifier: "replace" },
      { name: "weight", label: "Weight", values: ["light", "medium", "heavy", "massive"], affectsLayers: [0, 1, 3], promptModifier: "replace" },
      { name: "direction", label: "Direction", values: ["left-to-right", "right-to-left", "approaching", "passing-by"], affectsLayers: [1], promptModifier: "replace" },
    ],
    exclusions: ["no music", "no tonal elements", "no reverb"],
    duration: { min: 0.5, max: 4, default: 2 },
    recommendedBatchCount: 10,
    exportNaming: { template: "Trailer_Whoosh_{speed}_{weight}_{direction}_v{version}", variables: ["speed", "weight", "direction", "version"], separator: "_", caseStyle: "pascal" },
    isBuiltIn: true,
    isPublic: true,
    version: 1,
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
  },
];

export function getBuiltInRecipe(slug: string): SoundDesignRecipe | undefined {
  return BUILT_IN_RECIPES.find((r) => r.slug === slug);
}

export function getAllRecipes(): SoundDesignRecipe[] {
  return [...BUILT_IN_RECIPES];
}
